### ISSUE TITLE
can't run under fig

### ISSUE THREAD

**Issue by srobertson** [gliderlabs/docker-consul#35] opened 2014-11-10 19:42 UTC
I realize that this maybe an issue with fig/boot2docker more than docker-consul. But thought I start here to collect info in order to open a bug report.

I can run docker consul just fine from boot2docker on the command line

```
$docker run -t -i  -p 8400:8400 -p 8500:8500 -p 8600:53/udp -name consul progrium/consul   -server  -bootstrap
```

However if I try to autumate running consul and registrator in a dev enviroment using fig and this file.

```
consul:
  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
  image: progrium/consul
  hostname: node1
  name: consul
  command: -server  -bootstrap

registrator:
  links:
    - consul:consul
  hostname: dev.6sense.com
  image: progrium/registrator
  command: consul://consul:8500 --ttl 500
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock

```

I get the following  errors 

```
consul_1      |     2014/11/09 02:08:04 [ERR] raft: Failed to make RequestVote RPC to 172.17.0.89:8300: dial tcp 172.17.0.89:8300: no route to host
consul_1      |     2014/11/09 02:08:04 [ERR] raft: Failed to make RequestVote RPC to 172.17.0.89:8300: dial tcp 172.17.0.89:8300: no route to host
consul_1      |     2014/11/09 02:08:04 [ERR] raft: Failed to make RequestVote RPC to 172.17.0.89:8300: dial tcp 172.17.0.89:8300: no route to host
consul_1      |     2014/11/09 02:08:05 [ERR] http: Request /v1/health/service/demanda?passing=1&tag=production&wait=60000ms, error: No cluster leader
consul_1      |     2014/11/09 02:08:05 [ERR] http: Request /v1/health/service/demanda?passing=1&tag=staging&wait=60000ms, error: No cluster leader
consul_1      |     2014/11/09 02:08:05 [ERR] http: Request /v1/health/service/dataapi?passing=1&tag=staging&wait=60000ms, error: No cluster leader
consul_1      |     2014/11/09 02:08:05 [ERR] http: Request /v1/health/service/ui?passing=1&tag=production&wait=60000ms, error: No cluster leader
consul_1      |     2014/11/09 02:08:05 [ERR] http: Request /v1/health/service/ui?passing=1&tag=staging&wait=60000ms, error: No cluster leader
consul_1      |     2014/11/09 02:08:05 [WARN] raft: Election timeout reached, restarting election
consul_1      |     2014/11/09 02:08:05 [INFO] raft: Node at 172.17.0.93:8300 [Candidate] entering Candidate state
consul_1      |     2014/11/09 02:08:07 [WARN] raft: Election timeout reached, restarting election
consul_1      |     2014/11/09 02:08:07 [INFO] raft: Node at 172.17.0.93:8300 [Candidate] entering Candidate state
consul_1      |     2014/11/09 02:08:07 [ERR] raft: Failed to make RequestVote RPC to 172.17.0.89:8300: dial tcp 172.17.0.89:8300: no route to host
consul_1      |     2014/11/09 02:08:07 [ERR] raft: Failed to make RequestVote RPC to 172.17.0.89:8300: dial tcp 172.17.0.89:8300: no route to host
consul_1      |     2014/11/09 02:08:08 [WARN] raft: Election timeout reached, restarting election
consul_1      |     2014/11/09 02:08:08 [INFO] raft: Node at 172.17.0.93:8300 [Candidate] entering Candidate state
consul_1      |     2014/11/09 02:08:09 [WARN] raft: Election timeout reached, restarting election
consul_1      |     2014/11/09 02:08:09 [INFO] raft: Node at 172.17.0.93:8300 [Candidate] entering Candidate state
```

Is this related to the ARP issue?

**Comment by chr0n1x** [comment] 2015-01-09 20:28
I think that this is something that should be addressed in fig. I'm not quite sure what would have to be done on their end though...

**Comment by rkettelerij** [comment] 2015-05-08 09:52
Encountered this too and I can confirm removing containers (using `docker-compose rm`) works. It's unfortunate we need this though.

@mileswilson mentions docker compose just restarts containers but doesn't recreate them. At least in the latest version of docker-compose the opposite is true. `docker-compose up` will recreate containers unless ` --no-recreate` is passed as an argument. Nevertheless this doesn't change the issue at all since consul's cluster state still appears to be stale.

**Comment by andyshinn** [comment] 2015-12-16 21:56
This is just the way that Consul works. The state (containing the correct IP address of Consul self) is persisted because `docker-compose` does not remove the container. When the container is restarted, it has a new IP address. This would be a feature request for `docker-compose`.

**Closed by andyshinn** 2015-12-16 21:56 UTC

**Comment by ShaneDrury** [comment] 2016-04-19 21:31
A quick fix is also to remove `peers.json`, especially if you've mounted a data volume. Say your data volume is mounted at `/mnt/consul`, just remove `/mnt/consul/raft/peers.json` when consul has been stopped and it should re-establish communications.

**Comment by nijikokun** [comment] 2016-09-01 09:40
To anyone who finds this issue, setting `-data-dir /tmp/consul` will resolve the issue.
